services:
  culturarte:
    build: .
    container_name: culturarte-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_H2_CONSOLE_ENABLED: "true"
    volumes:
      - ./logs:/app/logs
